#!/bin/bash

if [ $# != 2 ]
then
	echo "Wrong no of arguments"
	exit 0
fi
if [ -e $1 ]
then
	if grep -z "$2" $1
	then
		echo "It is there"
	else
		echo "$2" >> $1
	fi
else
	echo "file Doesnt exist"
fi
