#!/bin/bash

echo "OS Informtion"
uname -a

echo "Available Shells: "
cat /etc/shells

echo "Mouse Information: "
cat /etc/sysconfig/mouse

echo "CPU Information:"
cat /proc/cpuinfo

echo "Memory Information:" 
cat /proc/meminfo

echo "Hard disk information:" 
echo "Model: `cat /sys/class/block/sda/device/model` "    
echo "Size: `cat /sys/class/block/sda/size` "    
echo "Cache size: `cat /proc/ide/hda/cache` "    

echo "File System (Mount):" 
cat /proc/mounts

